#pragma once

#include <freestanding/asm/unistd.h>

#define SYS_read __NR_read
#define SYS_write __NR_write
#define SYS_open __NR_open
#define SYS_close __NR_close
#define SYS_stat __NR_stat
#define SYS_fstat __NR_fstat
#define SYS_lstat __NR_lstat
#define SYS_poll __NR_poll
#define SYS_lseek __NR_lseek
#define SYS_mmap __NR_mmap
#define SYS_mprotect __NR_mprotect
#define SYS_munmap __NR_munmap
#define SYS_brk __NR_brk
#define SYS_rt_sigaction __NR_rt_sigaction
#define SYS_rt_sigprocmask __NR_rt_sigprocmask
#define SYS_rt_sigreturn __NR_rt_sigreturn
#define SYS_ioctl __NR_ioctl
#define SYS_pread64 __NR_pread64
#define SYS_readv __NR_readv
#define SYS_writev __NR_writev
#define SYS_pipe __NR_pipe
#define SYS_dup __NR_dup
#define SYS_dup2 __NR_dup2
#define SYS_nanosleep __NR_nanosleep
#define SYS_getitimer __NR_getitimer
#define SYS_setitimer __NR_setitimer
#define SYS_getpid __NR_getpid
#define SYS_sendfile __NR_sendfile
#define SYS_socket __NR_socket
#define SYS_connect __NR_connect
#define SYS_accept __NR_accept
#define SYS_sendto __NR_sendto
#define SYS_recvfrom __NR_recvfrom
#define SYS_shutdown __NR_shutdown
#define SYS_bind __NR_bind
#define SYS_listen __NR_listen
#define SYS_socketpair __NR_socketpair
#define SYS_fork __NR_fork
#define SYS_vfork __NR_vfork
#define SYS_execve __NR_execve
#define SYS_exit __NR_exit
#define SYS_wait4 __NR_wait4
#define SYS_kill __NR_kill
#define SYS_uname __NR_uname
#define SYS_fcntl __NR_fcntl
#define SYS_flock __NR_flock
#define SYS_getdents __NR_getdents
#define SYS_getcwd __NR_getcwd
#define SYS_chdir __NR_chdir
#define SYS_rename __NR_rename
#define SYS_mkdir __NR_mkdir
#define SYS_rmdir __NR_rmdir
#define SYS_link __NR_link
#define SYS_unlink __NR_unlink
#define SYS_symlink __NR_symlink
#define SYS_readlink __NR_readlink
#define SYS_chmod __NR_chmod
#define SYS_fchmod __NR_fchmod
#define SYS_chown __NR_chown
#define SYS_lchown __NR_lchown
#define SYS_umask __NR_umask
#define SYS_gettimeofday __NR_gettimeofday
#define SYS_getrlimit __NR_getrlimit
#define SYS_getrusage __NR_getrusage
#define SYS_times __NR_times
#define SYS_getuid __NR_getuid
#define SYS_getgid __NR_getgid
#define SYS_setuid __NR_setuid
#define SYS_setgid __NR_setgid
#define SYS_geteuid __NR_geteuid
#define SYS_getegid __NR_getegid
#define SYS_setpgid __NR_setpgid
#define SYS_getppid __NR_getppid
#define SYS_setsid __NR_setsid
#define SYS_seteuid __NR_seteuid
#define SYS_setegid __NR_setegid
#define SYS_getpgid __NR_getpgid
#define SYS_getsid __NR_getsid
#define SYS_utime __NR_utime
#define SYS_mknod __NR_mknod
#define SYS_arch_prctl __NR_arch_prctl
#define SYS_setrlimit __NR_setrlimit
#define SYS_settimeofday __NR_settimeofday
#define SYS_mount __NR_mount
#define SYS_umount __NR_umount
#define SYS_reboot __NR_reboot
#define SYS_sethostname __NR_sethostname
#define SYS_gethostname __NR_gethostname
#define SYS_tkill __NR_tkill
#define SYS_futex __NR_futex
#define SYS_getdents64 __NR_getdents64
#define SYS_set_tid_address __NR_set_tid_address
#define SYS_exit_group __NR_exit_group
#define SYS_tgkill __NR_tgkill
#define SYS_openat __NR_openat
#define SYS_fstatat __NR_fstatat
#define SYS_unlinkat __NR_unlinkat
#define SYS_symlinkat __NR_symlinkat
#define SYS_fchmodat __NR_fchmodat
#define SYS_utimensat __NR_utimensat
#define SYS_getsockopt __NR_getsockopt
#define SYS_setsockopt __NR_setsockopt
#define SYS_getrandom __NR_getrandom
