timeout: 5
default_entry: 1
mouse: no

/NullOS
	protocol: limine
	path: boot():/boot/nullkrnl
	module_path: boot():/boot/initrd.cpio.gz
	cmdline: quiet

# Warning: This enables debug messages, not an option for a kernel with debug symbols!
/NullOS (debug)
	protocol: limine
	path: boot():/boot/nullkrnl
	module_path: boot():/boot/initrd.cpio.gz
