#
# Boot config for NullOS
#
# Boots directly into the OS.
#

timeout: 0
quiet

/NullOS
	resolution: 800x600x32
	protocol: limine
	path: boot():/boot/nullkrnl
	module_path: boot():/boot/rootfs.tar.gz
