timeout: 5
interface_resolution: 800x600x32
wallpaper: boot():/boot/splash.jpg
term_font: boot():/boot/fonts/font8x15.bin
term_font_size: 8x15
term_font_spacing: 0
kaslr: on

/NullOS
	comment: Boot NullOS.
	resolution: 800x600x32
	protocol: limine
	path: boot():/boot/nullkrnl
	module_path: boot():/boot/rootfs.tar.gz

/NullOS (Debug)
	comment: Boot NullOS using serial port (COM1) for debugging.
	resolution: 800x600x32
	protocol: limine
	path: boot():/boot/nullkrnl
	module_path: boot():/boot/rootfs.tar.gz
	cmdline: serial=COM1